import{A as l,S as p}from"./assets/vendor-CkmpcuiD.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function d(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=d(e);fetch(e.href,t)}})();new l(".accordion-container");const o=document.querySelector(".swiper-wrapper");let c=null;fetch("https://paw-hut.b.goit.study/api/feedbacks").then(r=>r.json()).then(r=>{o.innerHTML="",r.feedbacks.forEach(s=>{o.insertAdjacentHTML("beforeend",`
        <div class="swiper-slide">
          <div class="feedback">
            <p class="feedback-text">${s.description}</p>
            <p class="feedback-author">— ${s.author}</p>
            <p class="feedback-rate">Rating: ${s.rate}</p>
          </div>
        </div>
      `)}),c?c.update():c=new p(".swiper",{pagination:{el:".swiper-pagination",clickable:!0,dynamicBullets:!0,dynamicMainBullets:3},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},breakpoints:{0:{slidesPerView:1},768:{slidesPerView:2}}})}).catch(r=>{o.innerHTML='<div class="swiper-slide">Failed to load feedbacks</div>',console.error(r)});const u=document.querySelector(".burger-btn"),i=document.getElementById("mobile-menu"),f=document.getElementById("data-burger-close");u.addEventListener("click",()=>{i.classList.add("open")});f.addEventListener("click",()=>{i.classList.remove("open")});i.addEventListener("click",r=>{r.target===i&&i.classList.remove("open")});document.addEventListener("keydown",r=>{r.key==="Escape"&&i.classList.contains("open")&&i.classList.remove("open")});
//# sourceMappingURL=index.js.map
