import{S as l,A as p}from"./assets/vendor-Qu3clCs0.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function d(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=d(e);fetch(e.href,t)}})();new l(".about-swiper",{loop:!0,pagination:{el:".about-controls .swiper-pagination",clickable:!0},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}});new p(".accordion-container");const o=document.querySelector(".slider .swiper-wrapper");let c=null;fetch("https://paw-hut.b.goit.study/api/feedbacks").then(r=>r.json()).then(r=>{o.innerHTML="",r.feedbacks.forEach(i=>{o.insertAdjacentHTML("beforeend",`
        <div class="swiper-slide">
          <div class="feedback">
            <p class="feedback-text">${i.description}</p>
            <p class="feedback-author">— ${i.author}</p>
            <p class="feedback-rate">Rating: ${i.rate}</p>
          </div>
        </div>
      `)}),c?c.update():c=new l(".slider .swiper",{pagination:{el:".controls .swiper-pagination",clickable:!0,dynamicBullets:!0,dynamicMainBullets:5},navigation:{nextEl:".swiper-but .swiper-button-next",prevEl:".swiper-but .swiper-button-prev"},breakpoints:{0:{slidesPerView:1},768:{slidesPerView:2}}})}).catch(r=>{o.innerHTML='<div class="swiper-slide">Failed to load feedbacks</div>',console.error(r)});const u=document.querySelector(".burger-btn"),s=document.getElementById("mobile-menu"),f=document.getElementById("data-burger-close");u.addEventListener("click",()=>{s.classList.add("open")});f.addEventListener("click",()=>{s.classList.remove("open")});s.addEventListener("click",r=>{r.target===s&&s.classList.remove("open")});document.addEventListener("keydown",r=>{r.key==="Escape"&&s.classList.contains("open")&&s.classList.remove("open")});
//# sourceMappingURL=index.js.map
